### PR TITLE
add parameters to command palete

### PR DESCRIPTION
**Pull request by MarekLew**
I added parameters to commands created for `" commandType ":" palette ". All parameters are separated by the `:` command

I did not test it properly, but I could run `workbench.action.tasks.runTask:mytaskname`

### CODE REVIEW

**Comment by MarekLew** [comment]
Sory wrong branch pullet.

**Comment by ppatotski** [comment]
I am not sure I understand what is going on here. I do not see any changes in 'Files Changed'. I see my several commits coming back to my branch.

**Comment by MarekLew** [comment]
This is wrong pull request.  Wrong branch pulled.

**Comment by MarekLew** [comment]
https://github.com/ppatotski/vscode-commandbar/pull/42/commits/395e08f8a13b510d9dddf86252aa37350c52faec

**Pull request closed without merging**
